[cli]
locustfile = "src/loadtest/locustfile.py"
rps_per_user = [50]
# num_workers = 3
run_time = "2m"
sps = 0
carbon_report_interval_seconds = 10
carbon_url_path = '/carbon'
carbon_report_path = 'src/loadtest/report'

[cli.local]
host = "http://localhost"
port = 8000

[cli.global]
host = "http://obelix30.cs.umass.edu"
port = 30080

[locust]
locustfile = "src/loadtest/locustfile.py"
headless = true
host = "http://localhost"
users = 6
# spawn-rate = 10
run-time = "2m"
processes = 6
expect-workers = 6
