[cli]
locustfile = "src/loadtest/locustfile.py"
sps = 0
carbon_report_interval_seconds = 10
carbon_url_path = 'carbon'
carbon_report_root_path = 'src/loadtest/report'

[rps]
# TODO: Need to figure out how to run test on 0rps
rps_per_users = [6.25, 12.5]

[cli.local]
service_root_url = "http://localhost:8000"

[cli.global]
app_root_url = "http://obelix30.cs.umass.edu:30080/api/v1"
tier2_root_url = "http://10.43.223.99/api/v1"

[locust]
locustfile = "src/loadtest/locustfile.py"
headless = true
host = "http://localhost"
users = 8
processes = 8
# spawn-rate = 10
# expect-workers = 8
run-time = "2m"
