[cli]
locustfile = "src/loadtest/locustfile.py"
rps_per_user = [50]
# num_workers = 3
run_time = "2m"
sps = 0
carbon_report_interval_seconds = 10
carbon_url_path = 'carbon'
carbon_report_path = 'src/loadtest/report'

[cli.local]
service_root_url = "http://localhost:8000"

[cli.global]
app_root_url = "http://obelix30.cs.umass.edu:30080/api/v1"
tier2_root_url = "http://10.43.223.99/api/v1"

[locust]
locustfile = "src/loadtest/locustfile.py"
headless = true
host = "http://localhost"
users = 6
# spawn-rate = 10
run-time = "2m"
processes = 6
expect-workers = 6
