[cli]
locustfile = "src/loadtest/locustfile.py"
is_local = false
is_report = true

[report]
is_report_locust_stats = false
report_per_second = 15
report_root_path = 'src/sinfonia_tier3_loadtest/report'

[network.local]
app_root_url = "http://localhost:8000"
tier2_root_url = "http://localhost:5000"

[network.global]
app_root_url = "http://192.168.245.32:30080/api/v1"
tier2_root_url = "http://192.168.245.32:30051/api/v1"

[load]
# TODO: Need to figure out how to run test on 0rps
num_concurrent_clients = 1
matrix_size = 100
is_generate_matrix = false
# rps_per_users = [0.1, 0.5, 1.0, 1.5, 2.0]
# rps_per_users = [1.0, 5.0, 10.0, 15.0, 20.0, 50.0]
rps_per_users = [10]
run_time = "140m"
users = 10
processes = 5
# expect_workers = 10
spawn_rate = 2
